# Main Work Experience Section
[work_experience]

# Experience Entry: Lucid Software
[work_experience.lucid_software]
description = '''# Lucid Software, 2022 - 2024
 *Software Engineer*
- Sole developer of android app for an educational platform.
- Notable features include document scanning using OpenCV.
- Learned Kotlin and applied in 1 month.
- Worked in a fast-paced team environment.'''

# Experience Entry: Freelance Projects
[work_experience.freelance_projects]
description = '''# Freelance Projects, 2020 - 2023
 *Software Engineer\/Project Manager*
- Managed and engineered multiple projects in *C\/C++* involving *Win32*.
- Used *python* to write high performance scripts for personal projects and commercial applications.
- Used *x86* assembly with *C* to write complicated hooking libraries and manipulate virtual memory.
- Experience in writing assembly and usage of intrinsics.
- Usage of *SQL* and *databases* and interoperability between *Java* and *C++*.
- Experience in graphics libraries like *DirectX* and *Vulkan*.
- Lots of experience *debugging* and *reverse engineering* application errors.'''

[about_page]
text = '''This is my portfolio project. It is meant to highlight my job history and previous projects as well as be a project in and of itself to show off my programming abilities in an interesting and engaging way.'''

[biography]
text = '''Hi, I'm Stuart an engineer from Acworth, Georgia, with a interest in solving complex software challenges. At Lucid Software, I took the lead on developing an Android app for an educational platform, diving headfirst into Kotlin and mastering it in just a month. This project was more than just coding for me; it involved integrating sophisticated document scanning features using OpenCV, showcasing my ability to quickly learn and apply new technologies to practical solutions.

During my time doing freelance work from 2020 to 2023, I had the opportunity to tackle a variety of projects both personal and for clients, primarily focusing on my strengths in C\/C++ and the Win32 API. I also ventured into Python to develop high-performance scripts for both personal and commercial projects. I also worked with x86 assembly and C to create advanced hooking libraries.

My skill set is broad and diverse, extending beyond coding. I've enjoyed sharing my knowledge through teaching Python and C++, and I'm proficient with a range of tools and languages, including C, Java, DirectX, and Vulkan for graphics. My GitHub features some of my notable projects, such as a library for virtual memory manipulation and a sandbox environment for reverse engineering kernel drivers.

My experience and deep understanding of the simplest attributes of a processor inform my abilities as a software engineer. I don't just write code I understand it, from text to assembly.

My academic journey began with earning a High School Diploma from Metro Academic Studies in 2022. Although it might seem modest, my real education has been through hands-on experience with coding and projects that challenge my abilities and push the boundaries of what I can achieve.

In summary, I'm a Engineer at heart who puts heart and hard work into everything I do. I've built a reputation as someone who learns quickly, approaches problems creatively, and tackles difficult challenges head-on. Whether working as part of a team or handling freelance projects, I'm all about finding innovative solutions and making technology work, one line of code at a time.'''
